apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "aws-efs.fullname" . }}
  labels:
    app: {{ template "aws-efs.fullname" . }}
    chart: {{ template "aws-efs.chart" . }}
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"

data:
  file.system.id: {{ .Values.provisioner.efsid }}
  aws.region: {{ .Values.provisioner.region }}
  provisioner.name: {{ .Values.provisioner.classname }}
