kind: StorageClass
apiVersion: storage.k8s.io/v1beta1
metadata:
  name: {{ template "aws-efs.fullname" . }}
  labels:
    app: {{ template "aws-efs.fullname" . }}
    chart: {{ template "aws-efs.chart" . }}
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"

provisioner: {{ .Values.provisioner.classname }}
