apiVersion: "v1"
kind: "List"
items:
  - kind: "Secret"
    apiVersion: "v1"
    metadata:
      name: "ldap-secret"
    data:
      # files in environment/* converted into base64 with file-to-base64.sh
      env.yaml: {{ .Files.Get "environment/my-env.yaml" | b64enc }}
      env.startup.yaml: {{ .Files.Get "environment/my-env-startup.yaml" | b64enc }}

        