apiVersion: v1
kind: Service
metadata:
  name: {{ template "openldap.fullname" . }}
  labels:
    app: {{ template "openldap.name" . }}
    chart: {{ template "openldap.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: openldap
      protocol: TCP
      name: openldap
  selector:
    app: {{ template "openldap.name" . }}
    release: {{ .Release.Name }}
