apiVersion: v1
kind: Secret
metadata:
  name: s3fs-secret
  namespace: default
type: Opaque
data:
  # base64 encoded keys
  # echo -n "AWS_KEY|AWS_SECRET_KEY" | base64
  aws-key: A=
  aws-secret-key: V
