apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "svn.fullname" . }}
  labels:
    app: {{ template "svn.name" . }}
    chart: {{ template "svn.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "svn.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "svn.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: s3synchronizer
          image: "{{ .Values.s3synchronizer.repository }}:{{ .Values.s3synchronizer.tag }}"
          imagePullPolicy: {{ .Values.s3synchronizer.pullPolicy }}
          securityContext:
            privileged: true
          env:
          - name: DUMB_INIT_VER
            value: 1.2.0
          - name: S3_BUCKET
            value: br-com-ihm-qa-svn
          - name: S3_REGION
            value: us-east-1
          - name: MNT_POINT
            value: /svn-config
          - name: AWS_KEY
            valueFrom:
              secretKeyRef:
                name: {{ .Values.s3synchronizer.secretName }}
                key: aws-key
          - name: AWS_SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: {{ .Values.s3synchronizer.secretName }}
                key: aws-secret-key
          volumeMounts:
          - name: devfuse
            mountPath: /dev/fuse
          - name: svn-config
            mountPath: /svn-config:shared

        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
          - name: app
            value: {{ template "svn.name" . }}
{{- if .Values.authentication.ldap.enabled -}}
          - name: ldap_host
            value: {{ .Values.authentication.ldap.ldap_host }}
          - name: ldap_bind_dn
            value: {{ .Values.authentication.ldap.ldap_bind_dn }}
          - name: ldap_bind_pass
            value: {{ .Values.authentication.ldap.ldap_bind_pass }}
          - name: ldap_uri
            value: {{ .Values.authentication.ldap.ldap_uri }}
{{- end }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          volumeMounts:
          - name: svn-config
            mountPath: /svn-config
          - name: svn-data
            mountPath: /svn
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      volumes:
      - name: devfuse
        hostPath:
          path: /dev/fuse
      - name: svn-config
        hostPath:
          path: /mnt/svn-config
      - name: svn-data
{{- if .Values.persistence.persistentVolumeClaim -}}
        persistentVolumeClaim:
          claimName: {{ .Values.persistentVolumeClaim.name }}
{{- else }}
        emptyDir: {}
{{- end }}

      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
